#
# Let's Chat Settings
#
# See defaults.yml for all available options
#

env: production # development / production

http:
  enable: true
  host: 'localhost' #'localhost' 192.168.137.1
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

files:
  enable: true
  provider: local
  local:
    dir: uploads

xmpp:
  enable: false
  port: 5222
  domain: example.com

database:
  uri: mongodb://localhost:27017/letschat

secrets:
  cookie: secretsauce
  
rooms:
  private: true

auth:
  providers: [local]
  local:
    enableRegistration: true
  # throttling:
  #   enable: true
  #   threshold: 3
